apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: convert
  template:
    metadata:
      labels:
        app: convert
    spec:
      containers:
      - name: convert
        image: joaoevalente97/conversao-temperatura:1.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: meuservice
spec:
  selector:
    app: convert
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort
